print(" ------------------------------------------------") 
print("|                                                |")
print("|    O1HelloWorld                                |")
print("|    Name : Menaal Hassan                        |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("Hello World") 
