print(" ------------------------------------------------")
print("|                                                |")
print("|    01HelloWorld                                |")
print("|    Name : Menaal Hassan                        |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("Hello World")