print(" ------------------------------------------------")
print("|                                                |")
print("|    02GoodbyeWorld                              |")
print("|    Name : Menaal Hassan                        |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("Hello World")
input("------> Program paused - press enter to continue")
print("GoodbyeWorld")